apiVersion: v1
kind: Pod
metadata:
  name: hello-world3
#  namespace: dz2
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
    - containerPort: 8080