kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-savchenko
  namespace: savchenko
subjects:
- kind: User
  name: test222 # должно совпадать с CN=test222
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-savchenko
  apiGroup: rbac.authorization.k8s.io