apiVersion: v1
kind: Pod
metadata:
  name: netology-web2
  namespace: dz2
  labels:
    app: netology2
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
    - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: netology-svc2
  namespace: dz2
spec:
  selector:
    app: netology2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 
