{
 "title": "New dashboard Copy1.2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "утилизация CPU для nodeexporter (в процентах, 100-idle);",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100",
     "legendFormat": "утилизация CPU для nodeexporter (в процентах, 100-idle);"
    }
   ]
  },
  {
   "title": "количество места на файловой системе.",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(device) (node_filesystem_avail_bytes{fstype!=\"tmpfs\"})",
     "legendFormat": "количество места на файловой системе."
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}",
     "legendFormat": "CPULA 1"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}\r",
     "legendFormat": "CPULA 5"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}",
     "legendFormat": "CPULA 15;"
    }
   ]
  },
  {
   "title": "количество свободной оперативной памяти;",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job='nodeexporter'}",
     "legendFormat": "количество свободной оперативной памяти;"
    }
   ]
  }
 ]
}