apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool
  labels:
#    app: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        command: ['sh', '-c', 'tail -f /multitool/log/test.txt']
        volumeMounts:
          - name: my-volume
            mountPath: "/multitool" # в поде

      - name: busybox
        image: busybox:1.28
        command: ['sh', '-c', 'mkdir /busybox/log && while true; do echo "$(date) - busybox-multitool" >> /busybox/log/test.txt; sleep 5; done']
        volumeMounts:
          - name: my-volume
            mountPath: "/busybox" # в поде
        ports:
        - containerPort: 80
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: task-pv-claim # на ноде

