apiVersion: v1
kind: Pod
metadata:
  name: netology-multitool
#  namespace: dz4
  labels:
    app: netology
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool
    ports:
    - containerPort: 8080
