apiVersion: v1
kind: Service
metadata:
  name: multitool-svc
#  namespace: dz4
spec:
  selector:
    app: nmt
  ports:
    - protocol: TCP
      name: multitool
      port: 1180
      targetPort: 1180