apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-nodeport-svc
#  namespace: dz4
spec:
  selector:
    app: nmt
  ports:
    - protocol: TCP
      name: nginx
      port: 80
      nodePort: 30080
    - protocol: TCP
      name: multitool
      port: 1180
      nodePort: 30081
  type: NodePort